<a href="https://colab.research.google.com/github/soniapachecomza/python-practica/blob/main/Act3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t4 = torch.tensor([
    [11, 12, 13],
    [13, 14, 15],
    [15, 16, 17],
    [17, 18, 19.]])
t4

tensor([[11., 12., 13.],
        [13., 14., 15.],
        [15., 16., 17.],
        [17., 18., 19.]])

In [7]:
t1.shape

torch.Size([])

In [8]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [9]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [10]:
print(t4)
t4.shape

tensor([[11., 12., 13.],
        [13., 14., 15.],
        [15., 16., 17.],
        [17., 18., 19.]])


torch.Size([4, 3])

#Tensor  operaciones con gradientes

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [12]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
y.backward()

In [14]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


#Interoperabilidad con Numpy

In [15]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [16]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [17]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [18]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

#Commit y upload en noteblock

In [19]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 KB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [20]:
import jovian

In [21]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
